import { ButtonLabels, Frame, FrameNumber, ScoreCard } from './types'

export const initialScoreCard: ScoreCard[] = [
  {
    name: 'Player 1',
    frames: [
      {
        frameNumber: 1,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 2,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 3,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 4,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 5,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 6,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 7,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 8,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 9,
        first: '',
        second: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
      {
        frameNumber: 10,
        first: '',
        second: '',
        third: '',
        didPrevFrameStrike: false,
        didPrevFrameSpare: false,
        totalScore: 0,
        nextTwoBowls: ['', ''],
      },
    ],
  },
]

export const initialFrames: Frame[] = [
  {
    frameNumber: 1,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 2,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]

export const labels: ButtonLabels[] = [
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
]
export const frameNumbers: FrameNumber[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
