import { Frame } from '@/constants/types'

export const frames: Frame[] = [
  {
    frameNumber: 1,
    first: 1,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 4,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 2,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 10,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]

export const framesWithOneStrike: Frame[] = [
  {
    frameNumber: 1,
    first: 1,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 4,
    nextTwoBowls: [3, 3],
  },
  {
    frameNumber: 2,
    first: 3,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 10,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: 10,
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: 8,
    second: 1,
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]
export const strikeFrame2: Frame[] = [
  {
    frameNumber: 1,
    first: 0,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 4,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 2,
    first: 10,
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 10,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: 2,
    second: 2,
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: 8,
    second: 1,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]

export const strikeFrame3: Frame[] = [
  {
    frameNumber: 1,
    first: 0,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 4,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 2,
    first: 2,
    second: 2,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 10,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: 10,
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: 8,
    second: 1,
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]

export const framesWithADoubleStrike: Frame[] = [
  {
    frameNumber: 1,
    first: 1,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 4,
    nextTwoBowls: [3, 3],
  },
  {
    frameNumber: 2,
    first: 3,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 10,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: 10,
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: 10,
    second: '',
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: 4,
    second: 4,
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: 3,
    second: 1,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]
export const framesWithATripleStrike: Frame[] = [
  {
    frameNumber: 1,
    first: 1,
    second: 3,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 4,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 2,
    first: 10,
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 10,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 3,
    first: 10,
    second: '',
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 4,
    first: 10,
    second: '',
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 5,
    first: 4,
    second: 4,
    didPrevFrameStrike: true,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 6,
    first: 3,
    second: 1,
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 7,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 8,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 9,
    first: '',
    second: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
  {
    frameNumber: 10,
    first: '',
    second: '',
    third: '',
    didPrevFrameStrike: false,
    didPrevFrameSpare: false,
    totalScore: 0,
    nextTwoBowls: ['', ''],
  },
]
